export { default as Sidebar } from './Sidebar/Sidebar'
export { default as Main } from './Main/Main'
export { default as Navigation } from './Navigation/Navigation'
export { default as Repo } from './Repo/Repo'
export { default as Loader } from './Loader/Loader'
export { default as Repos } from './Repos/Repos'
export { default as Followers } from './Followers/Followers'
